modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"
issueTrackerURL=""
[[mods]]
modId="greygoo"
version="1.0"
displayName="Grey Goo"
description='A modernized demo of the classic Grey Goo mod.'
